// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using HeybEticaret.DataAccess.Concrete.EfCore;

namespace HeybEticaret.DataAccess.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20190411114829_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HeybEticaret.Entities.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("HeybEticaret.Entities.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ImageUrl");

                b.Property<string>("Name");

                b.Property<decimal>("Price");

                b.HasKey("Id");

                b.ToTable("Products");
            });

            modelBuilder.Entity("HeybEticaret.Entities.ProductCategory", b =>
            {
                b.Property<int>("CategoryId");

                b.Property<int>("ProductId");

                b.HasKey("CategoryId", "ProductId");

                b.HasIndex("ProductId");

                b.ToTable("ProductCategory");
            });

            modelBuilder.Entity("HeybEticaret.Entities.ProductCategory", b =>
            {
                b.HasOne("HeybEticaret.Entities.Category", "Category")
                    .WithMany("ProductCategories")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("HeybEticaret.Entities.Product", "Product")
                    .WithMany("ProductCategories")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}